package com.example.utils

enum class AppLanguage(val displayName: String, val code: String, val flag: String) {
    ENGLISH("English", "en", "🇺🇸"),
    SPANISH("Español", "es", "🇪🇸"),
    FRENCH("Français", "fr", "🇫🇷"),
    GERMAN("Deutsch", "de", "🇩🇪"),
    JAPANESE("日本語", "ja", "🇯🇵")
}

object LanguageManager {

    private val translations = mapOf(
        AppLanguage.ENGLISH to mapOf(
            "app_name" to "LifeVault",
            "nav_notes" to "Notes",
            "nav_vault" to "Vault",
            "nav_search" to "Search",
            "nav_graph" to "Graph",
            "nav_scanner" to "Scanner",
            "nav_settings" to "Settings",
            "settings_title" to "Settings & Preferences",
            "theme_style_title" to "Visual Theme Style",
            "language_title" to "App Language",
            "security_title" to "Security & Authentication",
            "biometric_auth" to "Biometric Authentication",
            "auto_lock" to "Auto-Lock App on Inactivity",
            "backup_title" to "Database Backup & Export",
            "export_pdf" to "EXPORT PDF",
            "export_json" to "Export DB as JSON",
            "biometric_lock_title" to "LIFEVAULT SECURE ACCESS",
            "biometric_sub" to "Notes Vault is Encrypted",
            "biometric_desc" to "Biometric authentication required to unlock private notes & credentials",
            "scan_biometrics" to "SCAN BIOMETRICS",
            "enter_passcode" to "ENTER PASSCODE",
            "bypass_demo" to "BYPASS (DEMO)",
            "save" to "SAVE",
            "edit" to "Edit",
            "preview" to "Preview",
            "notebooks" to "Notebooks",
            "categories" to "Categories",
            "search_placeholder" to "Search notes, vault tags, or content...",
            "passwords_vault" to "Encrypted Password Vault",
            "add_password" to "+ Add Password",
            "copy_user" to "Copy Username",
            "copy_pass" to "Copy Password",
            "theme_cyberpunk" to "Cyberpunk Cyan (Default)",
            "theme_midnight" to "Velvet Midnight",
            "theme_emerald" to "Emerald Matrix",
            "theme_amber" to "Sunset Amber",
            "theme_oled" to "OLED High Contrast"
        ),
        AppLanguage.SPANISH to mapOf(
            "app_name" to "LifeVault",
            "nav_notes" to "Notas",
            "nav_vault" to "Bóveda",
            "nav_search" to "Buscar",
            "nav_graph" to "Gráfico",
            "nav_scanner" to "Escáner",
            "nav_settings" to "Ajustes",
            "settings_title" to "Ajustes y Preferencias",
            "theme_style_title" to "Estilo de Tema Visual",
            "language_title" to "Idioma de la Aplicación",
            "security_title" to "Seguridad y Autenticación",
            "biometric_auth" to "Autenticación Biométrica",
            "auto_lock" to "Bloqueo Automático",
            "backup_title" to "Copia de Seguridad y Exportación",
            "export_pdf" to "EXPORTAR PDF",
            "export_json" to "Exportar BD como JSON",
            "biometric_lock_title" to "ACCESO SEGURO LIFEVAULT",
            "biometric_sub" to "Bóveda de Notas Encriptada",
            "biometric_desc" to "Autenticación biométrica requerida para desbloquear notas privadas",
            "scan_biometrics" to "ESCANEAR BIOMETRÍA",
            "enter_passcode" to "INGRESAR CÓDIGO",
            "bypass_demo" to "OMITIR (DEMO)",
            "save" to "GUARDAR",
            "edit" to "Editar",
            "preview" to "Vista Previa",
            "notebooks" to "Cuadernos",
            "categories" to "Categorías",
            "search_placeholder" to "Buscar notas, etiquetas o contenido...",
            "passwords_vault" to "Bóveda de Contraseñas Encriptada",
            "add_password" to "+ Agregar Contraseña",
            "copy_user" to "Copiar Usuario",
            "copy_pass" to "Copiar Contraseña",
            "theme_cyberpunk" to "Cian Ciberpunk (Predeterminado)",
            "theme_midnight" to "Medianoche Terciopelo",
            "theme_emerald" to "Matriz Esmeralda",
            "theme_amber" to "Ámbar Atardecer",
            "theme_oled" to "Alto Contraste OLED"
        ),
        AppLanguage.FRENCH to mapOf(
            "app_name" to "LifeVault",
            "nav_notes" to "Notes",
            "nav_vault" to "Coffre",
            "nav_search" to "Chercher",
            "nav_graph" to "Graphe",
            "nav_scanner" to "Scanner",
            "nav_settings" to "Réglages",
            "settings_title" to "Réglages et Préférences",
            "theme_style_title" to "Style de Thème Visuel",
            "language_title" to "Langue de l'Application",
            "security_title" to "Sécurité et Authentification",
            "biometric_auth" to "Authentification Biométrique",
            "auto_lock" to "Verrouillage Automatique",
            "backup_title" to "Sauvegarde et Exportation",
            "export_pdf" to "EXPORTER PDF",
            "export_json" to "Exporter BD en JSON",
            "biometric_lock_title" to "ACCÈS SÉCURISÉ LIFEVAULT",
            "biometric_sub" to "Coffre de Notes Chiffré",
            "biometric_desc" to "Authentification biométrique requise pour déverrouiller les notes",
            "scan_biometrics" to "SCANNER BIOMÉTRIE",
            "enter_passcode" to "ENTRER CODE PIN",
            "bypass_demo" to "CONTOURNER (DEMO)",
            "save" to "ENREGISTRER",
            "edit" to "Éditer",
            "preview" to "Aperçu",
            "notebooks" to "Carnets",
            "categories" to "Catégories",
            "search_placeholder" to "Rechercher notes, tags ou contenu...",
            "passwords_vault" to "Coffre de Mots de Passe Chiffré",
            "add_password" to "+ Ajouter Mot de Passe",
            "copy_user" to "Copier Nom d'utilisateur",
            "copy_pass" to "Copier Mot de passe",
            "theme_cyberpunk" to "Cyberpunk Cyan (Défaut)",
            "theme_midnight" to "Minuit Velours",
            "theme_emerald" to "Matrice Émeraude",
            "theme_amber" to "Ambre Coucher de Soleil",
            "theme_oled" to "Haut Contraste OLED"
        ),
        AppLanguage.GERMAN to mapOf(
            "app_name" to "LifeVault",
            "nav_notes" to "Notizen",
            "nav_vault" to "Tresor",
            "nav_search" to "Suchen",
            "nav_graph" to "Graph",
            "nav_scanner" to "Scanner",
            "nav_settings" to "Einstellungen",
            "settings_title" to "Einstellungen & Optionen",
            "theme_style_title" to "Visueller Design-Stil",
            "language_title" to "App-Sprache",
            "security_title" to "Sicherheit & Authentifizierung",
            "biometric_auth" to "Biometrische Authentifizierung",
            "auto_lock" to "Automatische Sperre",
            "backup_title" to "Datenbanksicherung & Export",
            "export_pdf" to "PDF EXPORTIEREN",
            "export_json" to "DB als JSON exportieren",
            "biometric_lock_title" to "LIFEVAULT SICHERER ZUGRIFF",
            "biometric_sub" to "Notiz-Tresor ist verschlüsselt",
            "biometric_desc" to "Biometrische Authentifizierung zum Entsperren erforderlich",
            "scan_biometrics" to "BIOMETRIE SCANNEN",
            "enter_passcode" to "PIN EINGEBEN",
            "bypass_demo" to "UMGEHEN (DEMO)",
            "save" to "SPEICHERN",
            "edit" to "Bearbeiten",
            "preview" to "Vorschau",
            "notebooks" to "Notizbücher",
            "categories" to "Kategorien",
            "search_placeholder" to "Notizen, Tags oder Inhalt suchen...",
            "passwords_vault" to "Verschlüsselter Passwort-Tresor",
            "add_password" to "+ Passwort hinzufügen",
            "copy_user" to "Benutzername kopieren",
            "copy_pass" to "Passwort kopieren",
            "theme_cyberpunk" to "Cyberpunk Cyan (Standard)",
            "theme_midnight" to "Samt-Mitternacht",
            "theme_emerald" to "Smaragd-Matrix",
            "theme_amber" to "Sonnenuntergang-Bernstein",
            "theme_oled" to "OLED-Hochkontrast"
        ),
        AppLanguage.JAPANESE to mapOf(
            "app_name" to "LifeVault",
            "nav_notes" to "ノート",
            "nav_vault" to "ヴォールト",
            "nav_search" to "検索",
            "nav_graph" to "グラフ",
            "nav_scanner" to "スキャナー",
            "nav_settings" to "設定",
            "settings_title" to "設定と環境設定",
            "theme_style_title" to "ビジュアルテーマスタイル",
            "language_title" to "アプリの言語",
            "security_title" to "セキュリティと認証",
            "biometric_auth" to "生体認証",
            "auto_lock" to "自動ロック",
            "backup_title" to "データベースのバックアップとエクスポート",
            "export_pdf" to "PDFエクスポート",
            "export_json" to "JSONとしてDBエクスポート",
            "biometric_lock_title" to "LIFEVAULT セキュアアクセス",
            "biometric_sub" to "ノート保管庫は暗号化されています",
            "biometric_desc" to "プライベートノートのロック解除には生体認証が必要です",
            "scan_biometrics" to "生体認証スキャン",
            "enter_passcode" to "パスコード入力",
            "bypass_demo" to "バイパス (デモ)",
            "save" to "保存",
            "edit" to "編集",
            "preview" to "プレビュー",
            "notebooks" to "ノートブック",
            "categories" to "カテゴリー",
            "search_placeholder" to "ノート、タグ、内容を検索...",
            "passwords_vault" to "暗号化パスワード保管庫",
            "add_password" to "+ パスワード追加",
            "copy_user" to "ユーザー名をコピー",
            "copy_pass" to "パスワードをコピー",
            "theme_cyberpunk" to "サイバーパンクシアン (デフォルト)",
            "theme_midnight" to "ベルベットミッドナイト",
            "theme_emerald" to "エメラルドマトリックス",
            "theme_amber" to "サンセットアンバー",
            "theme_oled" to "OLEDハイコントラスト"
        )
    )

    fun getString(key: String, language: AppLanguage = AppLanguage.ENGLISH): String {
        val langMap = translations[language] ?: translations[AppLanguage.ENGLISH]
        return langMap?.get(key) ?: key
    }
}
